name: Upload Python Package

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install poetry
      uses: actions/checkout@master
      uses: actions/setup-python@v1
      uses: dschep/install-poetry-action@v1.2
      run: poetry run my_script.py

    - name: Install dependencies
      run: |
        poetry install

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry publish
